clone:
  path: github.com/NiotoMOto/joel

build:
  image:  mhart/alpine-node:6.5.0
  commands:
    - apk upgrade --update
    - apk add --no-cache make gcc g++ python
    - npm install -g gulp
    - npm install
    - gulp build
  environment:
    - DRONE_SERVER=http://drone.guillemoto.com
    - DRONE_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXh0IjoiTmlvdG9NT3RvIiwidHlwZSI6InVzZXIifQ.vi7SAkP18ekP4UVsozthjJnJdCdyZMoOfXq-wyMj3yc


cache:
  mount:
    - node_modules
    - .git

publish:
  docker:
    registry: registry.docker.guillemoto.com
    insecure: true
    repo: joel
    tag: latest
    storage_driver: aufs
    when:
      branch: drone-test
      event: commit

deploy:
  ssh:
    host: srv.guillemoto.com
    user: root
    port: 22
    commands:
      - docker pull registry.docker.guillemoto.com/joel:latest
      - docker rm -f -v joel
      - docker run --name joel -d --restart=always -p 4000:7000 registry.docker.guillemoto.com/joel:latest
    when:
      branch: drone-test
